name: Deploy Streamlit App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_web.txt
    
    - name: Test basic imports
      run: |
        python -c "import streamlit; print('✅ Streamlit import successful')"
        python -c "
        import sys
        sys.path.append('scripts')
        try:
            from PART3_OSM_DIJKSTRA import OSMDijkstraRAPTOR
            print('✅ PART3 import successful')
        except Exception as e:
            print(f'⚠️ PART3 import: {e}')
        "
    
    - name: Test app syntax
      run: |
        python -c "
        with open('streamlit_app.py', 'r') as f:
            compile(f.read(), 'streamlit_app.py', 'exec')
        print('✅ streamlit_app.py syntax valid')
        "

  # Uncomment for Streamlit Cloud deployment
  # deploy:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   
  #   steps:
  #   - name: Deploy to Streamlit Cloud
  #     run: echo "Deploy to https://share.streamlit.io/"